//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int approveId { get; set; }
        public Nullable<int> paperId { get; set; }
        public Nullable<int> userId { get; set; }
        public bool is_approved { get; set; }
        public Nullable<System.DateTime> approvedAt { get; set; }
    
        public virtual QuestionsPaper QuestionsPaper { get; set; }
        public virtual User User { get; set; }
        public virtual QuestionsPaper QuestionsPaper1 { get; set; }
    }
}
