//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstTodoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todolist
    {
        public Todolist() {
            DateTime dateTime = DateTime.Now; 

            DateTime dateOnly = dateTime.Date;
            CreatedAt = dateOnly;
            IsCompleted = false;
        }
        public int Id { get; set; }
        public string TaskDesc { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsCompleted { get; set; }
    }
}
